### PR TITLE
Models and Migrations

### LINKED ISSUE #16: Model Class for Questions
- [ ] Make a Model Class for Questions based off the ERD

https://dbdiagram.io/d/60144e0480d742080a386568

### LINKED ISSUE #17: Model Class for Categories
- [ ] Create a model class for Categories base off the ERD

https://dbdiagram.io/d/60144e0480d742080a386568

### LINKED ISSUE #18: Model Class for CategoryQuestion
- [ ] Create Model Class for CategoryQuestion based off the ERD

https://dbdiagram.io/d/60144e0480d742080a386568

### PR DESCRIPTION
**Pull request by egeehartz**
# Description

Added three models and migrated them
Took out user ids for the fixture that's included in this branch

Fixes # (issue)
closes #16 
closes #17 
closes #18 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by egeehartz** [comment]
Let me know of any opinions on character field length of the question texts!
Also related_names for the TopicQuestion module!

**Review by christopherjohnson1 — APPROVED** [review]
Models look good 👍

**Review by jmskinne — APPROVED** [review]
Looks good! ⭐

**Review by LukeZvada — APPROVED** [review]
Looks good!

**Pull request merged**
